server:
  port: ${PORT:8080}
spring:
  application:
    name: rabbit-mq
  datasource:
    url: jdbc:h2:mem:rabbit
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    #    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

